export {
  initialState,
  currentLines,
  updateState,
  mergeStates,
} from "./core";
export {
  CONFLICT_ADDED_LEFT,
  CONFLICT_ADDED_RIGHT,
  CONFLICT_ADDED_BOTH,
  CONFLICT_DELETED_LEFT,
  CONFLICT_DELETED_RIGHT,
  PEACE,
  conflictStrings,
  END_MARKER,
  showConflicts,
  conflictCode,
} from "./conflicts";
export { serializeState, deserializeState, type StateRow } from "./state";
export {
  parseTonicConflicts,
  parseTonicConflictsWithDiagnostics,
  conflictSummary,
  type ConflictBlock,
  type ConflictSegment,
} from "./conflictParser";
export {
  parseConflictLabel,
  formatConflictLabel,
  addTagToConflictLabel,
  removeTagFromConflictLabel,
  updateTagInConflictLabel,
  normalizeConflictLabel,
  sanitizeAuthorTagToken,
  type ConflictLabelMetadata,
} from "./markerLabel";
export {
  parseGitConflicts,
  parseGitConflictsWithDiagnostics,
  hasGitConflictMarkers,
} from "./gitConflictParser";
export {
  gitConflictBlocksToConflictRegions,
  gitConflictBlocksToTonicAnnotatedPreview,
  DEFAULT_GIT_MERGE_LEFT_INTENT,
  DEFAULT_GIT_MERGE_RIGHT_INTENT,
  type GitMergeHydrationOptions,
} from "./markerInterop";
export {
  resolveAuthorAliasForSide,
  humanAliasFromGitStdout,
  parseGitAuthorNameEmail,
  createDefaultGitAuthorProbe,
  type AuthorMode,
  type ResolveAuthorAliasParams,
} from "./authorAliasResolver";
export {
  loadIntentProfile,
  saveIntentProfile,
  parseIntentPair,
  promptIntentPairInteractive,
  DEFAULT_INTENT_PROFILE_PATH,
  type IntentProfileV1,
} from "./intentInteractive";
export {
  mergeSnapshots,
  annotatedToConflictFile,
  conflictRegionsToAnnotatedLines,
  conflictFileFromBlocks,
  heuristicResolvedLines,
  suggestionLineCountOk,
  applyTonicResolutions,
  applyTonicHeuristic,
  hydrateTonicAnnotatedAuthorIntent,
  type ConflictFile,
  type ConflictRegion,
  type TonicAuthorIntentHydration,
} from "./mergeUtils";
export {
  HYDRATION_INTENT_RESULT_SCHEMA,
  HYDRATION_CHROMADB_NPM_PACKAGE,
  HYDRATION_OPTIONAL_DEPENDENCY_GROUP,
  HYDRATION_PIPELINE_SCHEMA,
  HYDRATION_PIPELINE_VERSION,
  HYDRATION_OPTIONAL_AI_EXIT_CODE,
  HYDRATION_PIPELINE_STAGE_IDS,
  HydrationIndexer,
  HydrationRepository,
  buildHydrationAstCandidates,
  buildMissingOptionalAiDependencySkipResult,
  createHydrationChromaClient,
  buildHydrationRetrievalMerge,
  buildGuidedQuestionGenerationPrompt,
  buildHydrationSynthesisPrompt,
  createDefaultHydrationPipelineStages,
  createHydrationBranchIntentCollection,
  createHydrationCycleState,
  createHydrationPipelineRun,
  createHydrationQuestionPlan,
  defaultHydrationRunId,
  finalizeHydrationPipelineRun,
  formatHydrationPromptTemplate,
  getHydrationChromaCollection,
  isHydrationIndexStateCompatible,
  loadHydrationChromaModule,
  loadHydrationPipelineRun,
  loadConflictPrompts,
  loadHydrationPrompts,
  markStageArtifactWritten,
  parseHydrationChromaUrl,
  probeHydrationChromaHeartbeat,
  probeHydrationOptionalAiDependency,
  probeHydrationRuntimeReadiness,
  resolveHydrationRunDirectory,
  saveHydrationPipelineRun,
  updateHydrationPipelineStage,
  writeHydrationArtifact,
  type ConflictPromptBundle,
  type ChromaClientLike,
  type ChromaCollection,
  type HydrationArtifactPaths,
  type HydrationAstNodeKind,
  type HydrationBranchIntent,
  type HydrationBranchIntentCollection,
  type HydrationChromaHeartbeat,
  type HydrationChromaUrl,
  type HydrationCycleNode,
  type HydrationCycleState,
  type HydrationFuzzyAlignmentCandidate,
  type HydrationIndexSyncResult,
  type HydrationIntentTag,
  type HydrationMergedEvidence,
  type HydrationOptionalAiProbe,
  type HydrationPipelineArtifacts,
  type HydrationPipelineRun,
  type HydrationPipelineStageId,
  type HydrationPipelineStageState,
  type HydrationPromptBundle,
  type HydrationQuestionPlan,
  type HydrationQuestionSlot,
  type HydrationRepositoryFile,
  type HydrationRepositoryOptions,
  type HydrationRetrievalMerge,
  type HydrationRetrievalBundle,
  type HydrationRetrievalHit,
  type HydrationRunResult,
  type HydrationSkipReason,
  type HydrationStageStatus,
  type VectorBackendKind,
} from "./hydration";
