name: Publish py-action

on:
  workflow_dispatch:
    inputs:
      publish_pypi:
        required: true
        type: boolean
        default: false

jobs:
  publish:
    if: inputs.publish_pypi == true
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: pip install build
      - run: python -m build .
      - uses: pypa/gh-action-pypi-publish@release/v1
